// Normalized CDF data for dashboard visualizations
export interface CDFRecord {
  constituency: string;
  category: string;
  subCategory: string;
  amount: number;
}

// Helper function to parse amount strings to numbers
function parseAmount(amountStr: string): number {
  if (!amountStr || amountStr === "0" || amountStr === "") return 0;
  
  // Remove "K " prefix and commas, then parse
  const cleanAmount = amountStr.replace(/^K\s*/, "").replace(/,/g, "");
  const parsed = parseFloat(cleanAmount);
  return isNaN(parsed) ? 0 : parsed;
}

// Full, normalized CDF data
export const cdfData: CDFRecord[] = [
  // Central Province
  { constituency: "Katuba", category: "Bursaries", subCategory: "Secondary Boarding School", amount: 126000 },
  { constituency: "Keembe", category: "Bursaries", subCategory: "Secondary Boarding School", amount: 476011 },
  { constituency: "Keembe", category: "Bursaries", subCategory: "Skills Development", amount: 165150 },
  { constituency: "Katuba", category: "Bursaries", subCategory: "Skills Development", amount: 721731.8 },
  { constituency: "Kabwe Central", category: "Projects", subCategory: "Community Projects", amount: 13875699.29 },
  { constituency: "Kabwe Central", category: "Empowerment", subCategory: "Grants", amount: 490000 },
  { constituency: "Mkushi South", category: "Bursaries", subCategory: "Secondary Boarding School", amount: 456000 },
  { constituency: "Mkushi South", category: "Bursaries", subCategory: "Skills Development", amount: 380101 },
  { constituency: "Mumbwa", category: "Bursaries", subCategory: "Secondary School", amount: 1000 },
  { constituency: "Mumbwa", category: "Bursaries", subCategory: "Skills Development", amount: 206600 },
  { constituency: "Mumbwa", category: "Projects", subCategory: "Community Projects", amount: 3681946.91 },
  { constituency: "Lufubu", category: "Community Projects", subCategory: "N/A", amount: 1520000 },

  // Copperbelt Province
  { constituency: "Chililabombwe", category: "Bursaries", subCategory: "Secondary School", amount: 49500 },
  { constituency: "Chililabombwe", category: "Bursaries", subCategory: "Skills Development", amount: 2855198 },
  { constituency: "Chililabombwe", category: "Projects", subCategory: "Community Projects", amount: 15114024.68 },
  { constituency: "Chililabombwe", category: "Empowerment", subCategory: "Grants", amount: 1953199.8 },
  { constituency: "Chingola", category: "Bursaries", subCategory: "Secondary School", amount: 33000 },
  { constituency: "Chingola", category: "Bursaries", subCategory: "Skills Development", amount: 1203270 },
  { constituency: "Chingola", category: "Projects", subCategory: "Community Projects", amount: 13916550 },
  { constituency: "Chingola", category: "Empowerment", subCategory: "Grants", amount: 488700 },
  { constituency: "Kalulushi", category: "Bursaries", subCategory: "Secondary School", amount: 42000 },
  { constituency: "Kalulushi", category: "Bursaries", subCategory: "Skills Development", amount: 1048659 },
  { constituency: "Kalulushi", category: "Projects", subCategory: "Community Projects", amount: 13620000 },
  { constituency: "Kalulushi", category: "Empowerment", subCategory: "Grants", amount: 1953185 },
  { constituency: "Luanshya", category: "Bursaries", subCategory: "Secondary School", amount: 10000 },
  { constituency: "Luanshya", category: "Bursaries", subCategory: "Skills Development", amount: 4282822 },
  { constituency: "Luanshya", category: "Projects", subCategory: "Community Projects", amount: 11878581.74 },
  { constituency: "Luanshya", category: "Empowerment", subCategory: "Grants", amount: 1953200 },
  { constituency: "Lufwanyama", category: "Bursaries", subCategory: "Secondary School", amount: 103000 },
  { constituency: "Lufwanyama", category: "Bursaries", subCategory: "Skills Development", amount: 2347237 },
  { constituency: "Lufwanyama", category: "Projects", subCategory: "Community Projects", amount: 13935384.84 },
  { constituency: "Lufwanyama", category: "Empowerment", subCategory: "Grants", amount: 1955843.48 },
  { constituency: "Masaiti", category: "Bursaries", subCategory: "Secondary School", amount: 274000 },
  { constituency: "Masaiti", category: "Bursaries", subCategory: "Skills Development", amount: 1610194.5 },
  { constituency: "Masaiti", category: "Projects", subCategory: "Community Projects", amount: 13953384.84 },
  { constituency: "Masaiti", category: "Empowerment", subCategory: "Grants", amount: 1928961 },
  { constituency: "Mpongwe", category: "Bursaries", subCategory: "Secondary School", amount: 6600 },
  { constituency: "Mpongwe", category: "Bursaries", subCategory: "Skills Development", amount: 82986 },
  { constituency: "Mpongwe", category: "Projects", subCategory: "Community Projects", amount: 13916550 },
  { constituency: "Mpongwe", category: "Empowerment", subCategory: "Grants", amount: 1953199.9 },
  { constituency: "Mufulira", category: "Bursaries", subCategory: "Secondary School", amount: 42000 },
  { constituency: "Mufulira", category: "Bursaries", subCategory: "Skills Development", amount: 4069756.5 },
  { constituency: "Mufulira", category: "Projects", subCategory: "Community Projects", amount: 13916550 },
  { constituency: "Ndola Central", category: "Bursaries", subCategory: "Secondary School", amount: 9000 },
  { constituency: "Ndola Central", category: "Bursaries", subCategory: "Skills Development", amount: 2404468 },
  { constituency: "Ndola Central", category: "Projects", subCategory: "Community Projects", amount: 1500000 },

  // Eastern Province
  { constituency: "Chadiza", category: "Bursaries", subCategory: "Secondary School", amount: 214000 },
  { constituency: "Chadiza", category: "Bursaries", subCategory: "Skills Development", amount: 820964.47 },
  { constituency: "Chadiza", category: "Projects", subCategory: "Community Projects", amount: 13915938 },
  { constituency: "Chadiza", category: "Empowerment", subCategory: "Grants", amount: 1953200 },
  { constituency: "Chipata Central", category: "Bursaries", subCategory: "Secondary School", amount: 261600 },
  { constituency: "Chipata Central", category: "Bursaries", subCategory: "Skills Development", amount: 1384560 },
  { constituency: "Chipata Central", category: "Projects", subCategory: "Community Projects", amount: 13916550 },
  { constituency: "Chipata Central", category: "Empowerment", subCategory: "Grants", amount: 1952795 },
  { constituency: "Lundazi", category: "Bursaries", subCategory: "Secondary School", amount: 106000 },
  { constituency: "Lundazi", category: "Bursaries", subCategory: "Skills Development", amount: 279780 },
  { constituency: "Lundazi", category: "Projects", subCategory: "Community Projects", amount: 12716500 },
  { constituency: "Lundazi", category: "Empowerment", subCategory: "Grants", amount: 1953200 },
  { constituency: "Nyimba", category: "Bursaries", subCategory: "Secondary School", amount: 224000 },
  { constituency: "Nyimba", category: "Bursaries", subCategory: "Skills Development", amount: 317870 },
  { constituency: "Nyimba", category: "Projects", subCategory: "Community Projects", amount: 13916550 },
  { constituency: "Nyimba", category: "Empowerment", subCategory: "Grants", amount: 1953200 },
  { constituency: "Sinda", category: "Bursaries", subCategory: "Secondary Boarding", amount: 9300 },
  { constituency: "Sinda", category: "Bursaries", subCategory: "Skills Development", amount: 41590 },
  { constituency: "Sinda", category: "Empowerment", subCategory: "Grants", amount: 487115 },
  { constituency: "Sinda", category: "Community Projects", subCategory: "Development", amount: 196000 },

  // Lusaka Province
  { constituency: "Kafue", category: "Bursaries", subCategory: "Secondary Boarding School", amount: 70 },
  { constituency: "Kafue", category: "Bursaries", subCategory: "Skills Development", amount: 179 },
  { constituency: "Kafue", category: "Community Projects", subCategory: "N/A", amount: 4 },
  { constituency: "Kafue", category: "Empowerment", subCategory: "Grants", amount: 30 },
  { constituency: "Feira", category: "Bursaries", subCategory: "Secondary Boarding School", amount: 22 },
  { constituency: "Feira", category: "Bursaries", subCategory: "Skills Development", amount: 93 },
  { constituency: "Chawama", category: "Bursaries", subCategory: "Secondary Boarding School", amount: 3 },
  { constituency: "Kanyama", category: "Bursaries", subCategory: "Secondary Boarding School", amount: 47 },
  { constituency: "Kanyama", category: "Bursaries", subCategory: "Skills Development", amount: 222 },
  { constituency: "Kanyama", category: "Community Projects", subCategory: "N/A", amount: 2 },
  { constituency: "Mandevu", category: "Bursaries", subCategory: "Secondary Boarding School", amount: 17 },
  { constituency: "Mandevu", category: "Bursaries", subCategory: "Skills Development", amount: 306 },
  { constituency: "Munali", category: "Bursaries", subCategory: "Secondary Boarding School", amount: 17 },
  { constituency: "Rufunsa", category: "Bursaries", subCategory: "Secondary School", amount: 2288150 },
  { constituency: "Rufunsa", category: "Bursaries", subCategory: "Skills Development", amount: 252135 },
  { constituency: "Rufunsa", category: "Projects", subCategory: "Community Projects", amount: 10383212.07 },
  { constituency: "Rufunsa", category: "Empowerment", subCategory: "Grants", amount: 1953200 },
  { constituency: "Chongwe", category: "Projects", subCategory: "Community Projects", amount: 2844000 },
  { constituency: "Chongwe", category: "Empowerment", subCategory: "Grants", amount: 470084.66 },

  // Muchinga Province
  { constituency: "Chinsali", category: "Bursaries", subCategory: "Secondary School", amount: 138700 },
  { constituency: "Chinsali", category: "Bursaries", subCategory: "Skills Development", amount: 145072 },
  { constituency: "Chinsali", category: "Projects", subCategory: "Community Projects", amount: 13844550 },
  { constituency: "Chinsali", category: "Empowerment", subCategory: "Grants", amount: 1953200 },
  { constituency: "Isoka", category: "Bursaries", subCategory: "Secondary School", amount: 44000 },
  { constituency: "Isoka", category: "Bursaries", subCategory: "Skills Development", amount: 715795 },
  { constituency: "Isoka", category: "Projects", subCategory: "Community Projects", amount: 13916550 },
  { constituency: "Isoka", category: "Empowerment", subCategory: "Grants", amount: 1953200 },
  { constituency: "Kanchibiya", category: "Bursaries", subCategory: "Skills Development", amount: 0 },
  { constituency: "Kanchibiya", category: "Projects", subCategory: "Community Projects", amount: 13916550 },
  { constituency: "Kanchibiya", category: "Empowerment", subCategory: "Grants", amount: 1953200 },
  { constituency: "Mafinga", category: "Bursaries", subCategory: "Skills Development", amount: 646240 },
  { constituency: "Mafinga", category: "Empowerment", subCategory: "Grants", amount: 1950000 },
  { constituency: "Mpika", category: "Bursaries", subCategory: "Secondary School", amount: 391200 },
  { constituency: "Mpika", category: "Bursaries", subCategory: "Skills Development", amount: 1420021 },
  { constituency: "Mpika", category: "Empowerment", subCategory: "Grants", amount: 583449 },
  { constituency: "Nakonde", category: "Bursaries", subCategory: "Skills Development", amount: 71124 },
  { constituency: "Nakonde", category: "Projects", subCategory: "Community Projects", amount: 13916550 },
  { constituency: "Nakonde", category: "Empowerment", subCategory: "Grants", amount: 1953920 },
  { constituency: "Shiwa Ng'andu", category: "Bursaries", subCategory: "Secondary School", amount: 71000 },
  { constituency: "Shiwa Ng'andu", category: "Bursaries", subCategory: "Skills Development", amount: 2966009 },
  { constituency: "Shiwa Ng'andu", category: "Projects", subCategory: "Community Projects", amount: 13934338.38 },
  { constituency: "Shiwa Ng'andu", category: "Empowerment", subCategory: "Grants", amount: 1956233.23 },
  { constituency: "Mfuwe", category: "Bursaries", subCategory: "Secondary School", amount: 169200 },
  { constituency: "Mfuwe", category: "Bursaries", subCategory: "Skills Development", amount: 190227 },
  { constituency: "Mfuwe", category: "Projects", subCategory: "Community Projects", amount: 12935384.94 },
  { constituency: "Mfuwe", category: "Empowerment", subCategory: "Grants", amount: 1935000 },

  // Northwestern Province
  { constituency: "Chavuma", category: "Bursaries", subCategory: "Secondary School", amount: 286000 },
  { constituency: "Chavuma", category: "Bursaries", subCategory: "Skills Development", amount: 160764 },
  { constituency: "Chavuma", category: "Projects", subCategory: "Community Projects", amount: 13916550 },
  { constituency: "Chavuma", category: "Empowerment", subCategory: "Grants", amount: 450000 },
  { constituency: "Ikeleng'i", category: "Bursaries", subCategory: "Skills Development", amount: 276370 },
  { constituency: "Ikeleng'i", category: "Projects", subCategory: "Community Projects", amount: 4376500 },
  { constituency: "Ikeleng'i", category: "Empowerment", subCategory: "Grants", amount: 985000 },
  { constituency: "Kabompo", category: "Projects", subCategory: "Community Projects", amount: 3483845.84 },
  { constituency: "Kabompo", category: "Empowerment", subCategory: "Grants", amount: 488000 },
  { constituency: "Kasempa", category: "Bursaries", subCategory: "Secondary School", amount: 236780 },
  { constituency: "Kasempa", category: "Bursaries", subCategory: "Skills Development", amount: 974880 },
  { constituency: "Kasempa", category: "Projects", subCategory: "Community Projects", amount: 14649000 },
  { constituency: "Kasempa", category: "Empowerment", subCategory: "Grants", amount: 1953200 },
  { constituency: "Manyinga", category: "Bursaries", subCategory: "Secondary School", amount: 21000 },
  { constituency: "Manyinga", category: "Bursaries", subCategory: "Skills Development", amount: 121972 },
  { constituency: "Manyinga", category: "Projects", subCategory: "Community Projects", amount: 13916550 },
  { constituency: "Manyinga", category: "Empowerment", subCategory: "Grants", amount: 1930650 },
  { constituency: "Mufumbwe", category: "Bursaries", subCategory: "Secondary School", amount: 81000 },
  { constituency: "Mufumbwe", category: "Bursaries", subCategory: "Skills Development", amount: 1941540 },
  { constituency: "Mufumbwe", category: "Projects", subCategory: "Community Projects", amount: 13470000 },
  { constituency: "Mufumbwe", category: "Empowerment", subCategory: "Grants", amount: 1952459 },
  { constituency: "Mwinilunga", category: "Bursaries", subCategory: "Secondary School", amount: 60000 },
  { constituency: "Mwinilunga", category: "Bursaries", subCategory: "Skills Development", amount: 673003 },
  { constituency: "Mwinilunga", category: "Projects", subCategory: "Community Projects", amount: 13935384.84 },
  { constituency: "Mwinilunga", category: "Empowerment", subCategory: "Grants", amount: 1955840 },
  { constituency: "Solwezi Central", category: "Bursaries", subCategory: "Secondary School", amount: 546000 },
  { constituency: "Solwezi Central", category: "Bursaries", subCategory: "Skills Development", amount: 4324104 },
  { constituency: "Solwezi Central", category: "Projects", subCategory: "Community Projects", amount: 13900000 },
  { constituency: "Solwezi Central", category: "Empowerment", subCategory: "Grants", amount: 480000 },
  { constituency: "Solwezi West", category: "Bursaries", subCategory: "Secondary School", amount: 478200 },
  { constituency: "Solwezi West", category: "Bursaries", subCategory: "Skills Development", amount: 4487900 },
  { constituency: "Solwezi West", category: "Empowerment", subCategory: "Grants", amount: 1696250 },

  // Northern Province
  { constituency: "Chilubi", category: "Bursaries", subCategory: "Secondary School", amount: 307530 },
  { constituency: "Chilubi", category: "Bursaries", subCategory: "Skills Development", amount: 2000787.5 },
  { constituency: "Chilubi", category: "Projects", subCategory: "Community Projects", amount: 12716000 },
  { constituency: "Chilubi", category: "Empowerment", subCategory: "Grants", amount: 1924999.7 },
  { constituency: "Kaputa", category: "Bursaries", subCategory: "Secondary School", amount: 11000 },
  { constituency: "Kaputa", category: "Bursaries", subCategory: "Skills Development", amount: 1973727 },
  { constituency: "Kaputa", category: "Projects", subCategory: "Community Projects", amount: 13916550 },
  { constituency: "Kasama", category: "Bursaries", subCategory: "Secondary School", amount: 169500 },
  { constituency: "Kasama", category: "Bursaries", subCategory: "Skills Development", amount: 1782671.75 },
  { constituency: "Kasama", category: "Empowerment", subCategory: "Grants", amount: 1952845 },
  { constituency: "Lukashya", category: "Bursaries", subCategory: "Secondary School", amount: 139100 },
  { constituency: "Lukashya", category: "Bursaries", subCategory: "Skills Development", amount: 1569530.5 },
  { constituency: "Lukashya", category: "Empowerment", subCategory: "Grants", amount: 1950866 },
  { constituency: "Lunte", category: "Bursaries", subCategory: "Secondary School", amount: 9400 },
  { constituency: "Lunte", category: "Bursaries", subCategory: "Skills Development", amount: 1017323 },
  { constituency: "Lunte", category: "Projects", subCategory: "Community Projects", amount: 12716550 },
  { constituency: "Lupososhi", category: "Projects", subCategory: "Community Projects", amount: 10288810.4 },
  { constituency: "Lupososhi", category: "Empowerment", subCategory: "Grants", amount: 1953000 },
  { constituency: "Lubansenshi", category: "Bursaries", subCategory: "Secondary School", amount: 123000 },
  { constituency: "Lubansenshi", category: "Bursaries", subCategory: "Skills Development", amount: 415392 },
  { constituency: "Lubansenshi", category: "Projects", subCategory: "Community Projects", amount: 12716550 },
  { constituency: "Lubansenshi", category: "Empowerment", subCategory: "Grants", amount: 1372100 },
  { constituency: "Mbala", category: "Bursaries", subCategory: "Secondary School", amount: 16350 },
  { constituency: "Mbala", category: "Bursaries", subCategory: "Skills Development", amount: 98950 },
  { constituency: "Mbala", category: "Projects", subCategory: "Community Projects", amount: 13916550.5 },
  { constituency: "Mbala", category: "Empowerment", subCategory: "Grants", amount: 1920000 },
  { constituency: "Mporokoso", category: "Bursaries", subCategory: "Secondary School", amount: 66000 },
  { constituency: "Mporokoso", category: "Bursaries", subCategory: "Skills Development", amount: 120050 },
  { constituency: "Mporokoso", category: "Projects", subCategory: "Community Projects", amount: 13916550 },
  { constituency: "Mporokoso", category: "Empowerment", subCategory: "Grants", amount: 1949678 },
  { constituency: "Mpulungu", category: "Bursaries", subCategory: "Secondary School", amount: 9000 },
  { constituency: "Mpulungu", category: "Bursaries", subCategory: "Skills Development", amount: 298463 },
  { constituency: "Mpulungu", category: "Projects", subCategory: "Community Projects", amount: 12639400 },
  { constituency: "Chimbamilonga", category: "Bursaries", subCategory: "Secondary School", amount: 558000 },
  { constituency: "Chimbamilonga", category: "Bursaries", subCategory: "Skills Development", amount: 2148932 },
  { constituency: "Chimbamilonga", category: "Empowerment", subCategory: "Grants", amount: 1953955 },
  { constituency: "Senga Hill", category: "Bursaries", subCategory: "Secondary School", amount: 132600 },
  { constituency: "Senga Hill", category: "Bursaries", subCategory: "Skills Development", amount: 850408 },
  { constituency: "Senga Hill", category: "Projects", subCategory: "Community Projects", amount: 13916550 },
  { constituency: "Senga Hill", category: "Empowerment", subCategory: "Grants", amount: 1936625 },

  // Southern Province
  { constituency: "Chikankata", category: "Projects", subCategory: "Community Projects", amount: 13150000 },
  { constituency: "Chikankata", category: "Empowerment", subCategory: "Grants", amount: 1955843.48 },
  { constituency: "Chirundu", category: "Bursaries", subCategory: "Secondary School", amount: 45000 },
  { constituency: "Chirundu", category: "Bursaries", subCategory: "Skills Development", amount: 3340994 },
  { constituency: "Chirundu", category: "Projects", subCategory: "Community Projects", amount: 13915193.03 },
  { constituency: "Chirundu", category: "Empowerment", subCategory: "Grants", amount: 1466882.61 },
  { constituency: "Choma", category: "Bursaries", subCategory: "Secondary School", amount: 430620 },
  { constituency: "Choma", category: "Bursaries", subCategory: "Skills Development", amount: 675785 },
  { constituency: "Gwembe", category: "Bursaries", subCategory: "Secondary School", amount: 285360 },
  { constituency: "Gwembe", category: "Bursaries", subCategory: "Skills Development", amount: 170020 },
  { constituency: "Gwembe", category: "Empowerment", subCategory: "Grants", amount: 488959.96 },
  { constituency: "Itezhi-Tezhi", category: "Bursaries", subCategory: "Secondary School", amount: 100110 },
  { constituency: "Itezhi-Tezhi", category: "Bursaries", subCategory: "Skills Development", amount: 362710 },
  { constituency: "Itezhi-Tezhi", category: "Projects", subCategory: "Community Projects", amount: 11850000 },
  { constituency: "Itezhi-Tezhi", category: "Empowerment", subCategory: "Grants", amount: 1942719 },
  { constituency: "Kalomo Central", category: "Bursaries", subCategory: "Secondary School", amount: 589570 },
  { constituency: "Kalomo Central", category: "Bursaries", subCategory: "Skills Development", amount: 600883 },
  { constituency: "Kalomo Central", category: "Projects", subCategory: "Community Projects", amount: 13914505 },
  { constituency: "Kalomo Central", category: "Empowerment", subCategory: "Grants", amount: 1199500 },
  { constituency: "Dundumwenzi", category: "Bursaries", subCategory: "Secondary School", amount: 23905 },
  { constituency: "Dundumwenzi", category: "Bursaries", subCategory: "Skills Development", amount: 129196 },
  { constituency: "Dundumwenzi", category: "Empowerment", subCategory: "Grants", amount: 267000 },
  { constituency: "Katombola", category: "Bursaries", subCategory: "Skills Development", amount: 4516585 },
  { constituency: "Katombola", category: "Projects", subCategory: "Community Projects", amount: 8271550 },
  { constituency: "Katombola", category: "Empowerment", subCategory: "Grants", amount: 1953200 },
  { constituency: "Livingstone", category: "Bursaries", subCategory: "Secondary School", amount: 130070 },
  { constituency: "Livingstone", category: "Bursaries", subCategory: "Skills Development", amount: 1605325 },
  { constituency: "Livingstone", category: "Projects", subCategory: "Community Projects", amount: 10968314.14 },
  { constituency: "Livingstone", category: "Empowerment", subCategory: "Grants", amount: 1953200 },
  { constituency: "Mazabuka Central", category: "Bursaries", subCategory: "Skills Development", amount: 2377018 },
  { constituency: "Mazabuka Central", category: "Projects", subCategory: "Community Projects", amount: 13916550 },
  { constituency: "Magoye", category: "Empowerment", subCategory: "Grants", amount: 1466882.61 },
  { constituency: "Monze", category: "Projects", subCategory: "Community Projects", amount: 3483846.21 },
  { constituency: "Bweengwa", category: "Bursaries", subCategory: "Secondary School", amount: 111380 },
  { constituency: "Bweengwa", category: "Bursaries", subCategory: "Skills Development", amount: 438782 },
  { constituency: "Bweengwa", category: "Projects", subCategory: "Community Projects", amount: 13916550 },
  { constituency: "Bweengwa", category: "Empowerment", subCategory: "Grants", amount: 1464000 },
  { constituency: "Moomba", category: "Bursaries", subCategory: "Secondary School", amount: 32780 },
  { constituency: "Moomba", category: "Bursaries", subCategory: "Skills Development", amount: 42548 },
  { constituency: "Moomba", category: "Projects", subCategory: "Community Projects", amount: 10451538 },
  { constituency: "Moomba", category: "Empowerment", subCategory: "Grants", amount: 1950840 },
  { constituency: "Namwala", category: "Bursaries", subCategory: "Secondary School", amount: 102490 },
  { constituency: "Namwala", category: "Bursaries", subCategory: "Skills Development", amount: 44455 },
  { constituency: "Namwala", category: "Projects", subCategory: "Community Projects", amount: 10760103 },
  { constituency: "Namwala", category: "Empowerment", subCategory: "Grants", amount: 1937000 },
  { constituency: "Pemba", category: "Projects", subCategory: "Community Projects", amount: 13416550 },
  { constituency: "Pemba", category: "Empowerment", subCategory: "Grants", amount: 1953200 },
  { constituency: "Sinazongwe", category: "Bursaries", subCategory: "Secondary School", amount: 122745 },
  { constituency: "Sinazongwe", category: "Bursaries", subCategory: "Skills Development", amount: 627875 },
  { constituency: "Sinazongwe", category: "Projects", subCategory: "Community Projects", amount: 12000000 },
  { constituency: "Sinazongwe", category: "Empowerment", subCategory: "Grants", amount: 1160000 },
  { constituency: "Mapatizya", category: "Bursaries", subCategory: "Secondary School", amount: 145515 },
  { constituency: "Mapatizya", category: "Bursaries", subCategory: "Skills Development", amount: 160200 },
  { constituency: "Mapatizya", category: "Projects", subCategory: "Community Projects", amount: 13770516.71 },
  { constituency: "Mapatizya", category: "Empowerment", subCategory: "Grants", amount: 1953000 },

  // Western Province
  { constituency: "Kaoma", category: "Bursaries", subCategory: "Secondary School", amount: 882000 },
  { constituency: "Kaoma", category: "Bursaries", subCategory: "Skills Development", amount: 724160 },
  { constituency: "Kaoma", category: "Projects", subCategory: "Community Projects", amount: 11001617.49 },
  { constituency: "Kaoma", category: "Empowerment", subCategory: "Grants", amount: 1466775 },
  { constituency: "Luampa", category: "Bursaries", subCategory: "Secondary School", amount: 51000 },
  { constituency: "Luampa", category: "Bursaries", subCategory: "Skills Development", amount: 249000 },
  { constituency: "Luampa", category: "Projects", subCategory: "Community Projects", amount: 13649000 },
  { constituency: "Luampa", category: "Empowerment", subCategory: "Grants", amount: 1953000 },
  { constituency: "Lukulu East", category: "Bursaries", subCategory: "Secondary School", amount: 137865 },
  { constituency: "Lukulu East", category: "Bursaries", subCategory: "Skills Development", amount: 325190 },
  { constituency: "Lukulu East", category: "Projects", subCategory: "Community Projects", amount: 13916550 },
  { constituency: "Lukulu East", category: "Empowerment", subCategory: "Grants", amount: 1953200 },
  { constituency: "Mitete", category: "Projects", subCategory: "Community Projects", amount: 14085708 },
  { constituency: "Mitete", category: "Empowerment", subCategory: "Grants", amount: 388960 },
  { constituency: "Mongu Central", category: "Bursaries", subCategory: "Secondary School", amount: 1077000 },
  { constituency: "Mongu Central", category: "Bursaries", subCategory: "Skills Development", amount: 2034872 },
  { constituency: "Mongu Central", category: "Projects", subCategory: "Community Projects", amount: 13880377.43 },
  { constituency: "Mongu Central", category: "Empowerment", subCategory: "Grants", amount: 977921.74 },
  { constituency: "Mulobezi", category: "Bursaries", subCategory: "Skills Development", amount: 486500 },
  { constituency: "Mulobezi", category: "Projects", subCategory: "Community Projects", amount: 3667206.54 },
  { constituency: "Mulobezi", category: "Empowerment", subCategory: "Grants", amount: 488960 },
  { constituency: "Mwandi", category: "Bursaries", subCategory: "Secondary School", amount: 8000 },
  { constituency: "Mwandi", category: "Bursaries", subCategory: "Skills Development", amount: 832590 },
  { constituency: "Mwandi", category: "Empowerment", subCategory: "Grants", amount: 1785000 },
  { constituency: "Nalolo", category: "Bursaries", subCategory: "Secondary School", amount: 71340 },
  { constituency: "Nalolo", category: "Bursaries", subCategory: "Skills Development", amount: 1117778 },
  { constituency: "Nalolo", category: "Projects", subCategory: "Community Projects", amount: 13380192.88 },
  { constituency: "Nalolo", category: "Empowerment", subCategory: "Grants", amount: 1866000 },
  { constituency: "Senanga", category: "Bursaries", subCategory: "Secondary School", amount: 104000 },
  { constituency: "Senanga", category: "Bursaries", subCategory: "Skills Development", amount: 2081740 },
  { constituency: "Senanga", category: "Projects", subCategory: "Community Projects", amount: 13916000.34 },
  { constituency: "Senanga", category: "Empowerment", subCategory: "Grants", amount: 1953200 },
  { constituency: "Sesheke", category: "Bursaries", subCategory: "Secondary School", amount: 637000 },
  { constituency: "Sesheke", category: "Bursaries", subCategory: "Skills Development", amount: 127431 },
  { constituency: "Sesheke", category: "Projects", subCategory: "Community Projects", amount: 3483846.21 },
  { constituency: "Sesheke", category: "Empowerment", subCategory: "Grants", amount: 488960.87 },
  { constituency: "Shang'ombo", category: "Bursaries", subCategory: "Secondary School", amount: 6000 },
  { constituency: "Shang'ombo", category: "Bursaries", subCategory: "Skills Development", amount: 2085902 },
  { constituency: "Shang'ombo", category: "Projects", subCategory: "Community Projects", amount: 13916550 },
  { constituency: "Shang'ombo", category: "Empowerment", subCategory: "Grants", amount: 640567.62 },
  { constituency: "Sikongo", category: "Bursaries", subCategory: "Secondary School", amount: 1940000 },
  { constituency: "Sikongo", category: "Bursaries", subCategory: "Skills Development", amount: 95810 },
  { constituency: "Sikongo", category: "Projects", subCategory: "Community Projects", amount: 13849550 },
  { constituency: "Sikongo", category: "Empowerment", subCategory: "Grants", amount: 1940000 },
  { constituency: "Sioma", category: "Bursaries", subCategory: "Secondary School", amount: 16744 },
  { constituency: "Sioma", category: "Bursaries", subCategory: "Skills Development", amount: 1669683 },
  { constituency: "Sioma", category: "Projects", subCategory: "Community Projects", amount: 13916550 },
  { constituency: "Sioma", category: "Empowerment", subCategory: "Grants", amount: 230000 }
];

// Categories for filtering
export const CDF_CATEGORIES = [
  "Bursaries",
  "Projects", 
  "Empowerment",
  "Community Projects"
];

// Subcategories for each main category
export const CDF_SUBCATEGORIES = {
  "Bursaries": ["Secondary Boarding School", "Secondary School", "Skills Development"],
  "Projects": ["Community Projects"],
  "Empowerment": ["Grants"],
  "Community Projects": ["N/A", "Development"]
};

// Provinces mapping for better organization
export const CDF_PROVINCES = {
  "Central": ["Katuba", "Keembe", "Kabwe Central", "Mkushi South", "Mumbwa", "Lufubu"],
  "Copperbelt": ["Chililabombwe", "Chingola", "Kalulushi", "Luanshya", "Lufwanyama", "Masaiti", "Mpongwe", "Mufulira", "Ndola Central"],
  "Eastern": ["Chadiza", "Chipata Central", "Lundazi", "Nyimba", "Sinda"],
  "Lusaka": ["Kafue", "Feira", "Chawama", "Kanyama", "Mandevu", "Munali", "Rufunsa", "Chongwe"],
  "Muchinga": ["Chinsali", "Isoka", "Kanchibiya", "Mafinga", "Mpika", "Nakonde", "Shiwa Ng'andu", "Mfuwe"],
  "Northwestern": ["Chavuma", "Ikeleng'i", "Kabompo", "Kasempa", "Manyinga", "Mufumbwe", "Mwinilunga", "Solwezi Central", "Solwezi West"],
  "Northern": ["Chilubi", "Kaputa", "Kasama", "Lukashya", "Lunte", "Lupososhi", "Lubansenshi", "Mbala", "Mporokoso", "Mpulungu", "Chimbamilonga", "Senga Hill"],
  "Southern": ["Chikankata", "Chirundu", "Choma", "Gwembe", "Itezhi-Tezhi", "Kalomo Central", "Dundumwenzi", "Katombola", "Livingstone", "Mazabuka Central", "Magoye", "Monze", "Bweengwa", "Moomba", "Namwala", "Pemba", "Sinazongwe", "Mapatizya"],
  "Western": ["Kaoma", "Luampa", "Lukulu East", "Mitete", "Mongu Central", "Mulobezi", "Mwandi", "Nalolo", "Senanga", "Sesheke", "Shang'ombo", "Sikongo", "Sioma"]
}; 